### ISSUE TITLE
фирмваре ретракшин

### ISSUE THREAD

**Issue by Barconero** [Tombraider2006/K1#1]
у вас указано в профиль **филамента** вписывать код 
`SET_RETRACTION RETRACT_LENGTH=[filament_retraction_length] RETRACT_SPEED=[filament_retraction_speed] UNRETRACT_EXTRA_LENGTH=[filament_retract_restart_extra] UNRETRACT_SPEED=[filament_deretraction_speed]`

это не оптимально - нужно будет перезаписать все профили.
гораздо проще один раз в профиле принтера казать:
`SET_RETRACTION RETRACT_LENGTH=[retraction_length] RETRACT_SPEED=[retraction_speed] UNRETRACT_EXTRA_LENGTH=[retract_restart_extra] UNRETRACT_SPEED=[deretraction_speed]
RESPOND TYPE=command MSG="Retraction length set to [retraction_length]mm"
RESPOND TYPE=command MSG="Retract speed set to [retraction_speed]/[deretraction_speed]mm/c"`

тогда подхватятся все переопределения, а если их не было возьмутся значения из профиля принтера

**Comment by Tombraider2006** [comment]
спасибо, да. действительно должно получится лучше. как проверю, добавлю в мануал.
